[package]
name = "actix-todo"
version = "0.1.0"
authors = ["Rob Williams <rwilliams@spotify.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
serde = { version = "1.0.104", features = ["derive"] }