version: '3.1'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: actix
      POSTGRES_DB: todo
    ports:
      - 5432:5432